# Author: Matthieu Petiteau <mpetiteau.pro@gmail.com>
# In our nginx service with pass to our build the args
# DOMAIN and FLASK so we can populate our nginx server
# config automatically. see nginx/Dockerfile
version: "3.2"

services:
  nginx:
    build:
      context: ./nginx
      args:
        # Pass domain name and email from .env file
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
        # Pass the name of our docker-compose service to avoid having to update it in the
        # nginx files if we want to change it
        FLASK: application
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - application

  application:
    # APP_FOLDER = folder containing the app, loaded from .env file (`src` in this example)
    build: ./${APP_FOLDER}
    # FLASK_APP = flask entrypoint, loaded from .env file (`flask_app` in this example)
    command: gunicorn -c gunicorn.ini.py ${FLASK_APP}:app
    environment:
      # FLASK_ENV = flask environment, loaded from .env file
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - 5000:5000
